service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    DB_HOST: 'zooshop-db.cdqgcswpphtj.us-east-1.rds.amazonaws.com'
    DB_PORT: 5432
    DB_NAME: 'zooshop'
    DB_USERNAME: 'postgres'
    DB_PASSWORD: 'U9teZMt56grAyAvv1tK9'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'